In [66]:
import numpy as np
import pandas as pd
import matplotlib as mp

In [67]:
df=pd.read_csv("C:\\Users\\Ishan\\OneDrive\\Desktop\\E-comerce Analysis\\ecommerce_customer_data.csv")

In [68]:
df.shape

(2000, 9)

In [69]:
df.describe()

,Customer_ID,Age,Annual_Income,Spending_Score,Membership_Years,Online_Purchases,Discount_Usage,Churn
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,43.805500,84089.382500,50.448500,5.248000,97.976000,0.489155,0.310500
std,577.494589,14.929203,37446.608502,28.411793,2.759783,57.314858,0.281573,0.462814
min,1.000000,18.000000,20112.000000,1.000000,0.500000,1.000000,0.000000,0.000000
25%,500.750000,31.000000,50810.750000,25.000000,2.875000,50.000000,0.250000,0.000000
50%,1000.500000,44.000000,84476.500000,50.500000,5.200000,93.000000,0.480000,0.000000
75%,1500.250000,56.000000,115550.750000,75.250000,7.700000,147.000000,0.730000,1.000000
max,2000.000000,69.000000,149936.000000,99.000000,10.000000,199.000000,1.000000,1.000000

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       2000 non-null   int64
 1   Age               2000 non-null   int64
 2   Gender            2000 non-null   object
 3   Annual_Income     2000 non-null   int64
 4   Spending_Score    2000 non-null   int64
 5   Membership_Years  2000 non-null   float64
 6   Online_Purchases  2000 non-null   int64
 7   Discount_Usage    2000 non-null   float64
 8   Churn             2000 non-null   int64
dtypes: float64(2), int64(6), object(1)
memory usage: 140.8+ KB

In [71]:
df.isnull().sum()

Customer_ID         0
Age                 0
Gender              0
Annual_Income       0
Spending_Score      0
Membership_Years    0
Online_Purchases    0
Discount_Usage      0
Churn               0
dtype: int64

In [72]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Annual_Income', 'Spending_Score',
       'Membership_Years', 'Online_Purchases', 'Discount_Usage', 'Churn'],
      dtype='object')

In [73]:
df.columns=df.columns.str.lower()

In [74]:
df.columns=df.columns.str.replace(" " , "_")

In [75]:
df.columns

Index(['customer_id', 'age', 'gender', 'annual_income', 'spending_score',
       'membership_years', 'online_purchases', 'discount_usage', 'churn'],
      dtype='object')

In [76]:
df.describe()

,customer_id,age,annual_income,spending_score,membership_years,online_purchases,discount_usage,churn
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,43.805500,84089.382500,50.448500,5.248000,97.976000,0.489155,0.310500
std,577.494589,14.929203,37446.608502,28.411793,2.759783,57.314858,0.281573,0.462814
min,1.000000,18.000000,20112.000000,1.000000,0.500000,1.000000,0.000000,0.000000
25%,500.750000,31.000000,50810.750000,25.000000,2.875000,50.000000,0.250000,0.000000
50%,1000.500000,44.000000,84476.500000,50.500000,5.200000,93.000000,0.480000,0.000000
75%,1500.250000,56.000000,115550.750000,75.250000,7.700000,147.000000,0.730000,1.000000
max,2000.000000,69.000000,149936.000000,99.000000,10.000000,199.000000,1.000000,1.000000

In [77]:
!pip install pymysql mysql-connector-python pandas cryptography sqlalchemy

Requirement already satisfied: pymysql in c:\users\ishan\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: mysql-connector-python in c:\users\ishan\anaconda3\lib\site-packages (9.6.0)
Requirement already satisfied: pandas in c:\users\ishan\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: cryptography in c:\users\ishan\anaconda3\lib\site-packages (46.0.3)
Requirement already satisfied: sqlalchemy in c:\users\ishan\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ishan\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ishan\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ishan\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ishan\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: cffi>=2.0.0 in c:\users\ishan\anaconda3\lib\site-packages (from cryptography) (2.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\ishan\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ishan\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: pycparser in c:\users\ishan\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography) (2.23)
Requirement already satisfied: six>=1.5 in c:\users\ishan\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [78]:
# SQL JOINING
import mysql.connector
import pandas as pd
from mysql.connector import Error
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

In [79]:
url = URL.create(
    drivername="mysql+mysqlconnector",
    username="root",
    password="Ishan@9140",
    host="127.0.0.1",
    database="major"
)

In [80]:
engine = create_engine(url)
engine.connect()
print("Engine Connected")

table_name="customer"

# Upload data frame yo my sql
df.to_sql(table_name, engine, if_exists='replace', index=False)
print("CONNECTION SUCCESSFUL!")

Engine Connected
CONNECTION SUCCESSFUL!

In [81]:
df.describe()

,customer_id,age,annual_income,spending_score,membership_years,online_purchases,discount_usage,churn
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,43.805500,84089.382500,50.448500,5.248000,97.976000,0.489155,0.310500
std,577.494589,14.929203,37446.608502,28.411793,2.759783,57.314858,0.281573,0.462814
min,1.000000,18.000000,20112.000000,1.000000,0.500000,1.000000,0.000000,0.000000
25%,500.750000,31.000000,50810.750000,25.000000,2.875000,50.000000,0.250000,0.000000
50%,1000.500000,44.000000,84476.500000,50.500000,5.200000,93.000000,0.480000,0.000000
75%,1500.250000,56.000000,115550.750000,75.250000,7.700000,147.000000,0.730000,1.000000
max,2000.000000,69.000000,149936.000000,99.000000,10.000000,199.000000,1.000000,1.000000

In [82]:
df.head()

,customer_id,age,gender,annual_income,spending_score,membership_years,online_purchases,discount_usage,churn
0,1,56,Male,69812,88,3.2,92,0.43,1
1,2,69,Female,70500,26,4.3,30,0.23,1
2,3,46,Female,99151,17,8.2,199,0.52,0
3,4,32,Male,78643,71,0.6,153,0.25,0
4,5,60,Female,64900,13,6.7,127,0.94,0

In [83]:
print(df.columns)

Index(['customer_id', 'age', 'gender', 'annual_income', 'spending_score',
       'membership_years', 'online_purchases', 'discount_usage', 'churn'],
      dtype='object')

In [84]:
# Use 'spending_score' instead of 'Review Rating'
df['spending_score'] = df.groupby('annual_income')['spending_score'].transform(lambda x: x.fillna(x.median()))

In [85]:
print(df.columns)

Index(['customer_id', 'age', 'gender', 'annual_income', 'spending_score',
       'membership_years', 'online_purchases', 'discount_usage', 'churn'],
      dtype='object')

In [86]:
df.head()

,customer_id,age,gender,annual_income,spending_score,membership_years,online_purchases,discount_usage,churn
0,1,56,Male,69812,88,3.2,92,0.43,1
1,2,69,Female,70500,26,4.3,30,0.23,1
2,3,46,Female,99151,17,8.2,199,0.52,0
3,4,32,Male,78643,71,0.6,153,0.25,0
4,5,60,Female,64900,13,6.7,127,0.94,0

In [87]:
labels=['Young Adult', 'Adult', 'Middle-Aged', 'Senior']
df['age_group']=pd.qcut(df['age'], q=4, labels=labels)

In [88]:
df.head(20)

,customer_id,age,gender,annual_income,spending_score,membership_years,online_purchases,discount_usage,churn,age_group
0,1,56,Male,69812,88,3.2,92,0.43,1,Middle-Aged
1,2,69,Female,70500,26,4.3,30,0.23,1,Senior
2,3,46,Female,99151,17,8.2,199,0.52,0,Middle-Aged
3,4,32,Male,78643,71,0.6,153,0.25,0,Adult
4,5,60,Female,64900,13,6.7,127,0.94,0,Senior
5,6,25,Female,62946,69,6.9,193,0.91,0,Young Adult
6,7,38,Female,27851,26,8.1,115,0.57,0,Adult
7,8,56,Male,36288,49,9.4,6,0.35,0,Middle-Aged
8,9,36,Female,92692,67,0.7,18,0.38,1,Adult
9,10,40,Female,87580,7,2.0,10,0.41,0,Adult
10,11,28,Male,27368,58,8.9,92,0.73,0,Young Adult
11,12,28,Male,105436,49,4.9,139,0.45,0,Young Adult
12,13,41,Female,116136,53,5.9,193,0.86,1,Adult
13,14,53,Female,66403,65,6.8,77,0.94,0,Middle-Aged
14,15,57,Male,111170,62,7.0,101,0.34,0,Senior
15,16,41,Male,29168,17,9.4,84,0.56,1,Adult
16,17,20,Female,106497,43,10.0,193,0.10,0,Young Adult
17,18,39,Female,69879,25,7.3,52,0.20,0,Adult
18,19,19,Female,79871,3,3.2,195,0.41,1,Young Adult
19,20,41,Female,129632,79,8.9,31,0.21,0,Adult

In [89]:
#removes the row from the data-tabel
df=df.drop('age',axis=1)

In [90]:
df.head(50)

,customer_id,gender,annual_income,spending_score,membership_years,online_purchases,discount_usage,churn,age_group
0,1,Male,69812,88,3.2,92,0.43,1,Middle-Aged
1,2,Female,70500,26,4.3,30,0.23,1,Senior
2,3,Female,99151,17,8.2,199,0.52,0,Middle-Aged
3,4,Male,78643,71,0.6,153,0.25,0,Adult
4,5,Female,64900,13,6.7,127,0.94,0,Senior
5,6,Female,62946,69,6.9,193,0.91,0,Young Adult
6,7,Female,27851,26,8.1,115,0.57,0,Adult
7,8,Male,36288,49,9.4,6,0.35,0,Middle-Aged
8,9,Female,92692,67,0.7,18,0.38,1,Adult
9,10,Female,87580,7,2.0,10,0.41,0,Adult
10,11,Male,27368,58,8.9,92,0.73,0,Young Adult
11,12,Male,105436,49,4.9,139,0.45,0,Young Adult
12,13,Female,116136,53,5.9,193,0.86,1,Adult
13,14,Female,66403,65,6.8,77,0.94,0,Middle-Aged
14,15,Male,111170,62,7.0,101,0.34,0,Senior
15,16,Male,29168,17,9.4,84,0.56,1,Adult
16,17,Female,106497,43,10.0,193,0.10,0,Young Adult
17,18,Female,69879,25,7.3,52,0.20,0,Adult
18,19,Female,79871,3,3.2,195,0.41,1,Young Adult
19,20,Female,129632,79,8.9,31,0.21,0,Adult
20,21,Male,131623,29,1.0,145,0.88,1,Senior
21,22,Female,109388,32,2.7,183,0.16,0,Middle-Aged
22,23,Female,118646,26,9.0,110,0.46,0,Middle-Aged
23,24,Male,52174,16,2.9,93,0.61,1,Young Adult
24,25,Female,119751,25,2.6,164,0.69,0,Adult
25,26,Male,112491,54,1.8,154,0.38,1,Middle-Aged
26,27,Female,26581,28,8.7,53,0.87,1,Young Adult
27,28,Female,130155,73,5.3,145,0.57,1,Adult
28,29,Male,91853,56,6.9,86,0.44,1,Senior
29,30,Male,84046,65,2.8,153,0.07,0,Adult
30,31,Female,69678,93,7.7,2,0.46,1,Senior
31,32,Female,128392,86,7.7,86,0.82,0,Adult
32,33,Female,131250,80,3.5,133,0.61,0,Senior
33,34,Male,46649,41,4.4,4,0.83,1,Middle-Aged
34,35,Female,147795,51,2.5,164,0.49,0,Adult
35,36,Male,108668,71,9.8,6,0.12,0,Adult
36,37,Male,102325,78,6.6,149,0.01,0,Senior
37,38,Female,34567,29,9.4,118,0.30,0,Senior
38,39,Male,100404,83,3.4,89,0.70,1,Senior
39,40,Female,109906,19,7.9,154,0.79,0,Senior
40,41,Female,128069,66,7.8,183,0.30,0,Young Adult
41,42,Female,116019,41,7.1,167,0.50,1,Middle-Aged
42,43,Female,81944,45,9.7,161,0.42,0,Senior
43,44,Female,138428,15,4.2,14,0.41,0,Young Adult
44,45,Male,98002,3,1.7,56,0.23,0,Adult
45,46,Male,48803,11,6.9,81,0.14,0,Young Adult
46,47,Female,38230,53,7.4,149,0.20,0,Middle-Aged
47,48,Female,37862,46,6.0,46,0.06,1,Adult
48,49,Male,63355,30,2.5,144,0.20,0,Young Adult
49,50,Male,51259,57,5.3,16,0.01,1,Adult